# Generated by Django 2.0.8 on 2020-09-10 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 0, 40, 5, 608852)),
        ),
    ]
